{% set name = "fast-plscan" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fast_plscan-{{ version }}.tar.gz
  sha256: 034fbf0b79fe64703dd9e5a0812aecf374172fceb1c85c5df390a2923fbe44e8

build:
  number: 0
  skip: true                                # [py < 310 or py > 312]
  python_version_independent: true          # [py >= 312]
  script: 
    # Cross-compile builds don't support stub generation, disabled it for all builds for consistency
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation -C cmake.args="-DPython_EXECUTABLE=%PYTHON%" -C cmake.args='-DPLSCAN_CREATE_STUBS=OFF' # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation -C cmake.args="-DPython_EXECUTABLE=$PYTHON"  -C cmake.args='-DPLSCAN_CREATE_STUBS=OFF' -C cmake.args="-G=Ninja"    # [not win]
requirements:
  build:
    - cmake
    - ninja                                 # [not win]
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - scikit-build-core                     # [build_platform != target_platform]
    - setuptools-scm                        # [build_platform != target_platform]
    - nanobind                              # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - libgomp                               # [build_platform != target_platform and linux]
    - llvm-openmp                           # [build_platform != target_platform and osx]
  host:
    - pip
    - python
    - python-abi3                           # [py >= 312] 
    - python-gil
    - scikit-build-core
    - setuptools-scm
    - nanobind
    - libgomp                               # [linux]
    - llvm-openmp                           # [osx]
  run:
    - python
    - numpy >=2,<3
    - scipy >=1,<2
    - matplotlib-base >=3,<4
    - scikit-learn >=1.6,<2

test:
  imports:
    - fast_plscan
  commands:
    - pip check
    - abi3audit $SP_DIR/fast_plscan/_api.abi3.so -s -v --assume-minimum-abi3 3.12   # [unix and py >= 312]
    - abi3audit %SP_DIR%/fast_plscan/_api.pyd -s -v --assume-minimum-abi3 3.12      # [win  and py >= 312]
    - pytest . -k "not test_plots"  # plot tests are unstable and verified in github builds
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - abi3audit                               # [py >= 312]

about:
  summary: A fast multi-core implementation of the PLSCAN clustering algorithm.
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://github.com/jelmerbot/fast_plscan
  doc_url: https://fast-plscan.readthedocs.io/
  dev_url: https://github.com/jelmerbot/fast_plscan
  description: | 
    This package implements Persistent Leaf Spatial Clustering for Applications
    with Noise, a density-based clustering algorithm designed for exploratory
    data analyses. The algorithm identifies clusters that persist across
    multiple size scales, providing robust clustering results that are less
    sensitive to parameter choices.

extra:
  recipe-maintainers:
    - JelmerBot
